### ISSUE TITLE
Hello, we have set up an official fork on choosenim

### ISSUE THREAD

**Issue by ringabout** [ire4ever1190/choosenim#21]
https://github.com/nim-lang/choosenim

We have set up an official fork on choosenim. I just came accross your fork after ours have built the binaries successfully. How I wish we saw your fork early to save wasted efforts! Nice work!

**Comment by ire4ever1190** [comment]
Whoops I missed this issue 😅 apologies for not mentioning I had this fork earlier.

Will see if I can migrate some of my patches across
